### ISSUE TITLE
No valid sensor found

### ISSUE THREAD

**Issue by froggi1930** [TheFes/cheapest-energy-hours#170]
Since two days I can not process the data anymore...

```javascript
{% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %}
{% set output = cheapest_energy_hours(sensor='sensor.tibber_forecast', hours=6,mode = 'all') %}
{{output}}
``` 
will result in:
error: No valid sensor found

The template has not been changed:
```javascript
template:
  - trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: homeassistant
        event: start
    action:
      - service: tibber.get_prices
        data:
          start: "{{ (today_at() - timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S') }}"
          end: "{{ (today_at() + timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S') }}"
        response_variable: prices
    sensor:
      - name: tibber_forecast
        state: "{{ prices.prices.values() | first | selectattr('start_time', '<=', now()) | map(attribute='price') | list | last }}"
        attributes:
          prices: >
            {% set ns = namespace(prices=[]) %}
            {% for i in prices.prices.values() | first %}
              {% set n = dict(start_time = i.start_time.isoformat(), price = i.price) %}
              {% set ns.prices = ns.prices + [n] %}
            {% endfor %}
            {{ ns.prices }}
``` 

anybody else with this problem?

**Comment by froggi1930** [comment]
yes I am on 2024.11.0b5 right now

**Comment by froggi1930** [comment]
Log files says...

Logger: homeassistant.helpers.sensor
Quelle: helpers/trigger_template_entity.py:204
Erstmals aufgetreten: 19:12:46 (1 Vorkommnisse)
Zuletzt protokolliert: 19:12:46

Error rendering state template for sensor.tibber_forecast: TypeError: '<=' not supported between instances of 'str' and 'datetime.datetime'

**Comment by TheFes** [comment]
Yeah, I know what's wrong. Need to update the docimentation on this. 
Try:
```
template:
  - trigger:
      - platform: time_pattern
        hours: "/1"
      - platform: homeassistant
        event: start
    action:
      - service: tibber.get_prices
        data:
          start: "{{ (today_at() - timedelta(days=1)).strftime('%Y-%m-%d %H:%M:%S') }}"
          end: "{{ (today_at() + timedelta(days=2)).strftime('%Y-%m-%d %H:%M:%S') }}"
        response_variable: prices
    sensor:
      - name: tibber_forecast
        state: "{{ prices.prices.values() | first | selectattr('start_time', '<=', utcnow().isoformat()) | map(attribute='price') | list | last }}"
        attributes:
          prices: >
            {% set ns = namespace(prices=[]) %}
            {% for i in prices.prices.values() | first %}
              {% set n = dict(start_time = i.start_time.isoformat(), price = i.price) %}
              {% set ns.prices = ns.prices + [n] %}
            {% endfor %}
            {{ ns.prices }}
```

**Comment by TheFes** [comment]
They changed the output from the Tibber service call from datetime objects to datetime strings.

**Comment by froggi1930** [comment]
Morning Martijn,
unfortunately it still has an error message....
```javascript
Logger: homeassistant.helpers.sensor
Quelle: helpers/trigger_template_entity.py:204
Erstmals aufgetreten: 07:21:12 (1 Vorkommnisse)
Zuletzt protokolliert: 07:21:12

Error rendering state template for sensor.tibber_forecast: UndefinedError: 'str object' has no attribute 'isoformat'
```

**Comment by TheFes** [comment]
My bad, should be fixed now in the code above

**Comment by froggi1930** [comment]
I am back on 2024.10.4 right now. Will test again tonight...

**Comment by RalfPfitzner** [comment]
Hi TheFes,

I've tried your latest edit but still get the same error.
`Error while processing template: Template<template=({% from 'cheapest_energy_hours.jinja' import cheapest_energy_hours %} {% set output = cheapest_energy_hours(sensor='sensor.tibber_prices', hours=states('sensor.time_for_load'), start='now', end=today_at('06:00') + timedelta(days=1), look_ahead=true, include_tomorrow=true) %} {{ as_timestamp(output) | timestamp_custom('%H:%M', true) }}) renders=2>`
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 633, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2735, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 2, in top-level template code
  File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 394, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "cheapest_energy_hours.jinja", line 442, in template
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 750, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 635, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'`

Anyhow, thanks for providing your work :-)

**Comment by froggi1930** [comment]
I am now on 2024.11 and with your revised template it works again
